### ISSUE TITLE
Missing plugins for PostCSS 8

### ISSUE THREAD

**Issue by jonnitto** [CarbonPackages/Carbon.Pipeline#4]
(if marked, they are ready for version 8)

- [ ] [postcss-import-alias] – [Issue](https://github.com/privatenumber/postcss-import-alias/issues/1)
- [ ] [postcss-easy-import] – [Issue](https://github.com/TrySound/postcss-easy-import/issues/40)
- [ ] ~[postcss-preset-env] – [Issue](https://github.com/csstools/postcss-preset-env/issues/191)~
- [ ] ~[postcss-easing-gradients] – [Issue](https://github.com/larsenwork/postcss-easing-gradients/issues/12)~
- [ ] ~[postcss-for] – [Issue](https://github.com/antyakushev/postcss-for/issues/23)~
- [ ] ~[pleeease-filters] – [Issue](https://github.com/iamvdo/pleeease-filters/issues/20)~
- [ ] ~[postcss-quantity-queries] – [Issue](https://github.com/pascalduez/postcss-quantity-queries/issues/21)~

[postcss-import-alias]: https://www.npmjs.com/package/postcss-import-alias
[postcss-easy-import]: https://www.npmjs.com/package/postcss-easy-import
[postcss-preset-env]: https://preset-env.cssdb.org
[postcss-easing-gradients]: https://www.npmjs.com/package/postcss-easing-gradients
[postcss-for]: https://www.npmjs.com/package/postcss-for
[pleeease-filters]: https://www.npmjs.com/package/pleeease-filters
[postcss-quantity-queries]: https://www.npmjs.com/package/postcss-quantity-queries

**Comment by jonnitto** [comment]
Thanks to [commit a400255], [postcss-import-alias] and [postcss-easy-import] is not needed anymore.

[commit  a400255]: ../commit/a4002553e16c331e522660b42a43e533b740178f
[postcss-import-alias]: https://www.npmjs.com/package/postcss-import-alias
[postcss-easy-import]: https://www.npmjs.com/package/postcss-easy-import
